In [2]:
import pandas as pd
import pyvista as pv
import numpy as np
from pathlib import Path

In [3]:
def distance(x1, y1, z1, x2, y2, z2):
	"""
	Function to calculate distance between 2 3-d coordinates
	"""

	dist_sq = (x1-x2)**2 + (y1-y2)**2 + (z1-z2)**2
	dist = np.sqrt(dist_sq)

	return dist

In [6]:
baseDir = "/home/csi20local/Dropbox/phd/Projects/Stanford/Data/NAVx_Exports/S-0404 NAVx Export/2022_08_26_11_32_10"

## clr of UAC NAVx
clrPath=f"/home/csi20local/Dropbox/phd/Projects/Stanford/Data/DICOM_Gated_CT/S-0404/UAC_NAVx/clean-Labelled-refined-aligned.vtk"
uacPath="/home/csi20local/Dropbox/phd/Projects/Stanford/Data/DICOM_Gated_CT/S-0404/UAC_NAVx/Labelled_Coords_2D_Rescaling_v3_C_copy.vtk"

clr_aligned = pv.read(clrPath)
uac_msh = pv.read(uacPath)

Pipeline:

* read in p2p points
* calcualte nearest cell, and omit those which are too far away from the cell
* append said cell with p2p voltage
* do for all DxL files to make densest possible voltage map

In [7]:
## voltage point coords and P2P value
p2p_df_1 = pd.read_csv(f"{baseDir}/p2p_LA_DxL_1.txt")
p2p_df_2 = pd.read_csv(f"{baseDir}/p2p_LA_DxL_2.txt")
p2p_df_3 = pd.read_csv(f"{baseDir}/p2p_LA_DxL_3.txt")
p2p_df_4 = pd.read_csv(f"{baseDir}/p2p_LA_DxL_4.txt")
p2p_df_5 = pd.read_csv(f"{baseDir}/p2p_LA_DxL_5.txt")
p2p_df_6 = pd.read_csv(f"{baseDir}/p2p_LA_DxL_6.txt")
p2p_df_7 = pd.read_csv(f"{baseDir}/p2p_LA_DxL_7.txt")
p2p_df_8 = pd.read_csv(f"{baseDir}/p2p_LA_DxL_8.txt")
p2p_df_9 = pd.read_csv(f"{baseDir}/p2p_LA_DxL_9.txt")
p2p_df_10 = pd.read_csv(f"{baseDir}/p2p_LA_DxL_10.txt")
p2p_df_11 = pd.read_csv(f"{baseDir}/p2p_LA_DxL_11.txt")
p2p_df_12 = pd.read_csv(f"{baseDir}/p2p_LA_DxL_12.txt")
p2p_df_13 = pd.read_csv(f"{baseDir}/p2p_LA_DxL_13.txt")
p2p_df_14 = pd.read_csv(f"{baseDir}/p2p_LA_DxL_14.txt")
p2p_df_15 = pd.read_csv(f"{baseDir}/p2p_LA_DxL_15.txt")
p2p_df_16 = pd.read_csv(f"{baseDir}/p2p_LA_DxL_16.txt")

In [8]:
num_DxL_files=16
p2p_all = np.zeros((num_DxL_files, p2p_df_1.shape[0], p2p_df_1.shape[1]))
p2p_all[0, ...] = p2p_df_1.to_numpy()
p2p_all[1, ...] = p2p_df_2.to_numpy()
p2p_all[2, ...] = p2p_df_3.to_numpy()
p2p_all[3, ...] = p2p_df_4.to_numpy()
p2p_all[4, ...] = p2p_df_5.to_numpy()
p2p_all[5, ...] = p2p_df_6.to_numpy()
p2p_all[6, ...] = p2p_df_7.to_numpy()
p2p_all[7, ...] = p2p_df_8.to_numpy()
p2p_all[8, ...] = p2p_df_9.to_numpy()
p2p_all[9, ...] = p2p_df_10.to_numpy()
p2p_all[10, ...] = p2p_df_11.to_numpy()
p2p_all[11, ...] = p2p_df_12.to_numpy()
p2p_all[12, ...] = p2p_df_13.to_numpy()
p2p_all[13, ...] = p2p_df_14.to_numpy()
p2p_all[14, ...] = p2p_df_15.to_numpy()
p2p_all[15, ...] = p2p_df_16.to_numpy()

In [9]:
p2p_all.shape[1]

256

In [10]:
## closest point indices of cLr msh for each voltage point
msh_pt_IDS = np.zeros((num_DxL_files, p2p_all.shape[1]))

In [11]:
## distances to each closest point
msh_pt_dist = np.zeros((num_DxL_files, p2p_all.shape[1]))

In [14]:
## Get closest msh point IDs for all DxL files

for dxl_j in range(0, num_DxL_files):
    print("dxl_j: ", dxl_j)

    for i in range(0, 256):
        ## point ID
        ans = clr_aligned.find_closest_point((p2p_all[dxl_j, i, 0], p2p_all[dxl_j, i, 1], p2p_all[dxl_j, i, 2]))
        msh_pt_IDS[dxl_j, i] = ans

        ## Get point coords
        point_coords = clr_aligned.points[ans]
        point_coords = np.array(point_coords)

        ## Distance between closest point snap and voltage coord
        dist = distance(point_coords[0], point_coords[1], point_coords[2],
                        p2p_all[dxl_j, i, 0], p2p_all[dxl_j, i, 1], p2p_all[dxl_j, i, 2])
        msh_pt_dist[dxl_j, i] = dist

dxl_j:  0
dxl_j:  1
dxl_j:  2
dxl_j:  3
dxl_j:  4
dxl_j:  5
dxl_j:  6
dxl_j:  7
dxl_j:  8
dxl_j:  9
dxl_j:  10
dxl_j:  11
dxl_j:  12
dxl_j:  13
dxl_j:  14
dxl_j:  15


In [18]:
p2p_all[11, ...]

array([[-5.20280e+01, -3.24860e+01,  3.95886e+02,  1.41000e-01],
       [-5.20000e+01, -3.55100e+01,  3.97772e+02,  1.42000e-01],
       [-5.19640e+01, -3.15830e+01,  3.93974e+02,  2.30000e-02],
       ...,
       [-5.17700e+01, -5.56020e+01,  4.01971e+02,  6.60000e-02],
       [-5.51240e+01, -5.61610e+01,  3.93040e+02,  1.44000e-01],
       [-5.99290e+01, -5.21370e+01,  3.94025e+02,  4.21000e-01]])

In [24]:
msh_pt_dist.shape

(16, 256)

In [25]:
msh_pt_dist

array([[158.73796986,  14.93702509,   9.77071197, ...,   2.33880801,
          5.9728224 ,   1.24867407],
       [  2.69002654,   0.87531039,   0.46455237, ...,   3.085911  ,
          1.30248646,   2.87862181],
       [  3.37432947,   0.3147449 ,   0.9598388 , ...,   7.41556083,
          2.44503172,   2.35822981],
       ...,
       [  1.7186923 ,   2.12310055,   2.47366213, ...,   1.55000214,
          1.74446324,   1.75802764],
       [  1.89645051,   0.3545409 ,   0.2377301 , ...,  16.06083027,
         15.07753784,   8.88502422],
       [ 12.78670957,  10.43366378,  12.2802715 , ...,   9.66100922,
          6.87246582,   1.60973362]])

In [28]:
## Filter out points too far away

upper_limit=10.0
condition = msh_pt_dist[...] < upper_limit

In [30]:
np.sum(condition)

3406

In [31]:
16*256

4096

In [34]:
condition.shape

(16, 256)

In [35]:
msh_pt_IDS.shape

(16, 256)

In [38]:
msh_pt_IDS[condition]

array([ 38334., 124023., 127515., ...,  36035., 139755.,  16182.])

In [39]:
p2p_all.shape

(16, 256, 4)

In [41]:
p2p_only = p2p_all[..., -1]

In [42]:
p2p_only.shape

(16, 256)

In [44]:
p2p_only[condition].shape

(3406,)

In [47]:
msh_pt_IDS[condition].shape[0]

3406