This notebook explores the eigen analysis of the strains, specifically how they compare to the fiber directions.

*  Do the fiber directions align with the principal strain directions?
*  Are the deformation isotropic or anisotropic? 

In [1]:
import pyvista as pv
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
## Define paths for reading in eigennalaysis
basePath = "/home/csi20/Dropbox/phd/Data/RG_CT_Cases/CT-CRT/case18"
trackingPath = f"{basePath}/MT-HiRes/SW-0.0-BE-1e-9"

## Read in tracked mesh for fiber directions
msh=pv.read(f"{trackingPath}/cLr-fibres-aligned-4.vtp")

In [3]:
## Read in eigenanalysis resutls
evectors_df = pd.read_csv(f"{trackingPath}/strain-eigenvectors-t4.txt", skiprows=3, names=['eigenvectors'])
evalues_df = pd.read_csv(f"{trackingPath}/strain-eigenvalues-t4.txt", skiprows=3, names=['eigenvalues'])

In [4]:
## Store 
result = np.zeros((1, 3, 3))

for i in range(0, 1):
    
    evectors_df.iloc[i][0]
    my_list = evectors_df.iloc[0][0].split(" ")
    my_list_2 = [i.replace('[','').replace(']','').replace('(','').replace(')','') for i in my_list]
    my_list_3 = [s for s in my_list_2 if s]
    
    # Convert the list to a numpy array of floats
    my_array = np.array(my_list_3, dtype=float)

    # Reshape the array into a 3x3 matrix
    my_matrix = my_array.reshape(3, 3)

    # Transpose the matrix to get three 3-dimensional column vectors
    my_vectors = my_matrix

    result[i, :, :] = my_vectors

In [5]:
result

array([[[-0.886398, -0.184316, -0.424647],
        [ 0.451781, -0.144383, -0.880368],
        [-0.100954,  0.972204, -0.211252]]])

In [6]:
evalue_list = evalues_df.iloc[0][0].split(" ")
evalue_list_2 = [s for s in evalue_list if s]
evalue_list_2

evalue_array = np.array(evalue_list_2, dtype=float)

In [7]:
evalue_array

array([5.61845e-02, 2.37437e-09, 1.39939e-01])

In [14]:
# Add the eigenvalues as a new column to the result array
eig_data = np.column_stack((result, evalue_array))

# Print the combined data
print(eig_data)

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 3 dimension(s) and the array at index 1 has 2 dimension(s)

In [15]:
import numpy as np

# Define the eigenvectors and eigenvalues
eigenvectors = np.array([[-0.886398, -0.184316, -0.424647],
                         [ 0.451781, -0.144383, -0.880368],
                         [-0.100954,  0.972204, -0.211252]])

eigenvalues = np.array([5.61845e-02, 2.37437e-09, 1.39939e-01])

# Add the eigenvalues as a new column to the eigenvectors array
eig_data = np.column_stack((eigenvectors, eigenvalues))

# Print the combined data
print(eig_data)

[[-8.86398e-01 -1.84316e-01 -4.24647e-01  5.61845e-02]
 [ 4.51781e-01 -1.44383e-01 -8.80368e-01  2.37437e-09]
 [-1.00954e-01  9.72204e-01 -2.11252e-01  1.39939e-01]]


In [13]:
import numpy as np

# Define the eigenvectors and eigenvalues
eigenvectors = np.array([[-0.886398, -0.184316, -0.424647],
                         [ 0.451781, -0.144383, -0.880368],
                         [-0.100954,  0.972204, -0.211252]])

eigenvalues = np.array([5.61845e-02, 2.37437e-09, 1.39939e-01])

# Add the eigenvalues as a new column to the eigenvectors array
eig_data = np.column_stack((eigenvectors, eigenvalues))

# Print the combined data
print(eig_data)

[[-8.86398e-01 -1.84316e-01 -4.24647e-01  5.61845e-02]
 [ 4.51781e-01 -1.44383e-01 -8.80368e-01  2.37437e-09]
 [-1.00954e-01  9.72204e-01 -2.11252e-01  1.39939e-01]]


In [11]:
## Store 
result = np.zeros((df.shape[0], 3, 3))

for i in range(0, df.shape[0]):
    
    df.iloc[i][0]
    my_list = df.iloc[0][0].split(" ")
    my_list_2 = [i.replace('[','').replace(']','').replace('(','').replace(')','') for i in my_list]
    my_list_3 = [s for s in my_list_2 if s]
    
    # Convert the list to a numpy array of floats
    my_array = np.array(my_list_3, dtype=float)

    # Reshape the array into a 3x3 matrix
    my_matrix = my_array.reshape(3, 3)

    # Transpose the matrix to get three 3-dimensional column vectors
    my_vectors = my_matrix.T

    result[i, :, :] = my_vectors

In [12]:
result

array([[[-0.886398,  0.451781, -0.100954],
        [-0.184316, -0.144383,  0.972204],
        [-0.424647, -0.880368, -0.211252]],

       [[-0.886398,  0.451781, -0.100954],
        [-0.184316, -0.144383,  0.972204],
        [-0.424647, -0.880368, -0.211252]],

       [[-0.886398,  0.451781, -0.100954],
        [-0.184316, -0.144383,  0.972204],
        [-0.424647, -0.880368, -0.211252]],

       ...,

       [[-0.886398,  0.451781, -0.100954],
        [-0.184316, -0.144383,  0.972204],
        [-0.424647, -0.880368, -0.211252]],

       [[-0.886398,  0.451781, -0.100954],
        [-0.184316, -0.144383,  0.972204],
        [-0.424647, -0.880368, -0.211252]],

       [[-0.886398,  0.451781, -0.100954],
        [-0.184316, -0.144383,  0.972204],
        [-0.424647, -0.880368, -0.211252]]])

In [13]:
result.shape

(302616, 3, 3)

In [18]:
msh.cell_data["endo_avg"][0, :]

pyvista_ndarray([-0.04255443, -0.98918335,  0.14037603])

In [22]:
result[0, :, 0]

array([-0.886398, -0.184316, -0.424647])

In [23]:
np.dot(msh.cell_data["endo_avg"][0, :], result[0, :, 0])

0.1604322155954618